
columns = [
    'vaalipiiri_tai_maakuntanro',
    'vaalipiirin_tai_maakunnan_lyhenne_suomeksi',
    'pysyvä_puoluetunniste',
    'vakiopuoluenumero',
    'listajärjestysnumero',
    'vaaliliittonumero',
    'puolueen_tairyhmän_nimilyhenne_suomeksi',
    'ehdokasnumero',
    'kunnan_taivaalipiirin_tai_maakunnan_tai_äänestysalueen_nimi_suomeksi',
    'henkilön_etunimi',
    'henkilön_sukunimi',
    'sukupuoli',
    'ikä_vaalipäivänä',
    'ammatti',
    'kotikunnan_koodi',
    'kotikunnan_nimi_suomeksi',
    'ehdokkaan_äidinkieli',
    'europarlamentaarikko',
    'kansanedustaja',
    'kunnanvaltuutettu',
    'vaalitapahtuman_nimilyhenne_1_vertailuvaali',
    'ääniä_1_vertailuvaali',
]
